GET  http://localhost:4000/


### create new places
POST http://localhost:4000/country_town/new
Content-Type: application/json

{
    "title": "Lithuania"    
    
}

## get new places

#### USERS
GET http://localhost:4000/country_town
